format = """
$directory$git_branch$git_status$java$gradle$maven$golang$nodejs$docker_context
$character"""

[directory]
truncation_length = 4

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[java]
symbol = "☕ "

[gradle]
symbol = "🐘 "

[maven]
symbol = "🍃 "

[golang]
symbol = "🐹 "

[nodejs]
symbol = "⬡ "

[docker_context]
symbol = "🐳 "
